### ISSUE TITLE
analysis folder doesn't auto-create

### ISSUE THREAD

**Issue by bettinardi** [gregorbj/FSDM#4]
I just tried to "Save Results" under "Analyze Results".  The GUI crashed because it did not find the "analysis" folder under the model I was working on.  I created the "analysis" folder in the model folder I was working in by hand, and the save worked correctly.  I think the fix is to auto create that folder when the model is first built.

While I am capturing image saving issues - I would also note that the "Save Graph" button under the "Relations Graph Format" page doesn't work for me (nothing happens, it doesn't crash or report anything, and I can't find a saved graph if it is indeed saving an image).

**Comment by gregorbj** [comment]
Resolved
